//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QrCodeGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QrCodeGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime is later than EndTime.
        /// </summary>
        internal static string Error_iCal_StartTime_Bigger {
            get {
                return ResourceManager.GetString("Error_iCal_StartTime_Bigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your birthday is in the future?.
        /// </summary>
        internal static string Error_Invalid_Birthday {
            get {
                return ResourceManager.GetString("Error_Invalid_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address has invalid format.
        /// </summary>
        internal static string Error_Invalid_Email_Format {
            get {
                return ResourceManager.GetString("Error_Invalid_Email_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number has invalid format.
        /// </summary>
        internal static string Error_Invalid_Phone {
            get {
                return ResourceManager.GetString("Error_Invalid_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is invalid.
        /// </summary>
        internal static string Error_InvalidUrl {
            get {
                return ResourceManager.GetString("Error_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is missing.
        /// </summary>
        internal static string Error_Missing_Email {
            get {
                return ResourceManager.GetString("Error_Missing_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is missing.
        /// </summary>
        internal static string Error_Missing_Phone {
            get {
                return ResourceManager.GetString("Error_Missing_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is Missing.
        /// </summary>
        internal static string Error_Missing_Required_Field {
            get {
                return ResourceManager.GetString("Error_Missing_Required_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is missing.
        /// </summary>
        internal static string Error_MissingUrl {
            get {
                return ResourceManager.GetString("Error_MissingUrl", resourceCulture);
            }
        }
    }
}
